name: Deploy GCP cloud function

on:
  push:
    branches:
      - main
    paths:
      - "functions/src/**.ts"
      - "functions/package-lock.json"
      - "functions/package.json"
      - ".github/workflows/gcp-functions-deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "form"
          runtime: "nodejs16"
          region: "us-west3"
